language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo apt-get update -qq
install:
  # See issue travis-ci/travis-ci#1379
  - 'if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; export CXX="g++-4.8" CC="gcc-4.8"; fi'
  # CMake
  - sudo apt-get install -qq cmake
  # Google Protobuf
  - sudo apt-get install -qq protobuf-compiler libprotobuf-dev
  # GLFW
  - git clone https://github.com/glfw/glfw.git
  - sudo apt-get install -qq xorg-dev libgl1-mesa-dev libglu1-mesa-dev
  - cd glfw && git checkout 3.1 && cmake . && make && sudo make install && cd ..
script:
  - mkdir build
  - cd build
  - cmake .. -G "Unix Makefiles"
  - make -j8
